# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 1 * * *' # Runs every day at 1 AM UTC
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TOKEN_DRI: ${{ secrets.TOKEN_DRI }}

    steps:
    - uses: actions/checkout@v3
    - run : echo ${{ vars.URI }}
    - name: Set up Git
      run: |
        git config --global user.name ${{ secrets.USERNAME }}
        git config --global user.email ${{ secrets.EMAIL }}
          
    - name: Set environment variable
      run: echo "URI=${{ vars.URI }}" >> $GITHUB_ENV
    - name: Run script
      run: node index.js
    - name: push
      run: git add output && git commit -a -m "fetch" && echo "https://${{ secrets.TOKEN_DRI }}@github.com" > .git-credentials && git push 

